name: wkdev-sdk-test
on:
  push:
    branches: [ main, tag/** ]
    paths-ignore: [ docs/*, README.md]
  pull_request:
    paths-ignore: [ docs/*, README.md]
  create:
defaults:
  run:
    shell: bash
jobs:
  builda64:
    runs-on: [self-hosted, arm64]
    steps:
      - name: Set tag name
        run: |
          if [ "${GITHUB_BASE_REF}" = 'main' ]; then
            echo "WKDEV_SDK_TAG=arm64" >> "${GITHUB_ENV}"
          fi
          echo "WKDEV_SDK_CONTAINER_REGISTRY_USER_NAME=$(echo ${GITHUB_REPOSITORY_OWNER} | tr '[:upper:]' '[:lower:]')" >> "${GITHUB_ENV}"

      - name: Install podman
        #run: sudo apt-get update && sudo apt-get -y install podman fuse-overlayfs
        run: ubuntu_version='22.04'
          key_url="https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}/Release.key"
          sources_url="https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_${ubuntu_version}"

          echo "deb $sources_url/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list
          curl -fsSL $key_url | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/devel_kubic_libcontainers_unstable.gpg > /dev/null
          apt update
          apt install podman fuse-overlayfs



      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build image
        run: |
          source ./register-sdk-on-host.sh
          wkdev-sdk-bakery --mode=build --verbose
          wkdev-sdk-bakery --mode=export --verbose

      - name: Archive image
        uses: actions/upload-artifact@v4
        with:
          name: wkdev-sdk-a64.tar
          path: wkdev-sdk-a64.tar
          retention-days: 7

      - name: Test image
        run: |
          CONTAINER="wkdev-$(date +%s)"
          source ./register-sdk-on-host.sh
          wkdev-create --create-home --home ${HOME}/${CONTAINER}-home --verbose --attach --no-pull --name ${CONTAINER}
          wkdev-enter -n ${CONTAINER} --exec -- git clone --depth=1 https://github.com/WebKit/WebKit.git
          wkdev-enter -n ${CONTAINER} --exec -- ./WebKit/Tools/Scripts/build-webkit --wpe --release --generate-project-only
          wkdev-enter -n ${CONTAINER} --exec -- ./WebKit/Tools/Scripts/build-webkit --gtk --release --generate-project-only
          podman stop ${CONTAINER} || true
          podman rm ${CONTAINER} || true
          rm -rf ${HOME}/${CONTAINER}-home
  buildintel:
    runs-on: [self-hosted, x64]
    steps:
      - name: Set tag name
        run: |
          if [ "${GITHUB_BASE_REF}" = 'main' ]; then
            echo "WKDEV_SDK_TAG=intel" >> "${GITHUB_ENV}"
          fi
          echo "WKDEV_SDK_CONTAINER_REGISTRY_USER_NAME=$(echo ${GITHUB_REPOSITORY_OWNER} | tr '[:upper:]' '[:lower:]')" >> "${GITHUB_ENV}"

      - name: Install podman
        run: sudo apt-get update && sudo apt-get -y install podman fuse-overlayfs

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build image
        run: |
          source ./register-sdk-on-host.sh
          wkdev-sdk-bakery --mode=build --verbose
          wkdev-sdk-bakery --mode=export --verbose

      - name: Archive image
        uses: actions/upload-artifact@v4
        with:
          name: wkdev-sdk-intel.tar
          path: wkdev-sdk-intel.tar
          retention-days: 7

      - name: Test image
        run: |
          CONTAINER="wkdev-$(date +%s)"
          source ./register-sdk-on-host.sh
          wkdev-create --create-home --home ${HOME}/${CONTAINER}-home --verbose --attach --no-pull --name ${CONTAINER}
          wkdev-enter -n ${CONTAINER} --exec -- git clone --depth=1 https://github.com/WebKit/WebKit.git
          wkdev-enter -n ${CONTAINER} --exec -- ./WebKit/Tools/Scripts/build-webkit --wpe --release --generate-project-only
          wkdev-enter -n ${CONTAINER} --exec -- ./WebKit/Tools/Scripts/build-webkit --gtk --release --generate-project-only
          podman stop ${CONTAINER} || true
          podman rm ${CONTAINER} || true
          rm -rf ${HOME}/${CONTAINER}-home

  deploy:
    runs-on: self-hosted
    needs: [builda64, buildintel]
    if: github.ref_name == 'main' || startsWith(github.ref_name, 'tag/')
    steps:
      - name: Set tag name
        run: |
          if [ "${GITHUB_BASE_REF}" = 'main' ]; then
            echo "WKDEV_SDK_TAG=latest" >> "${GITHUB_ENV}"
          fi
          echo "WKDEV_SDK_CONTAINER_REGISTRY_USER_NAME=$(echo ${GITHUB_REPOSITORY_OWNER} | tr '[:upper:]' '[:lower:]')" >> "${GITHUB_ENV}"
          echo "REPO=$WKDEV_SDK_CONTAINER_REGISTRY_USER_NAME/wkdev-sdk" >> "${GITHUB_ENV}"

      - name: Install podman
        run: sudo apt-get update && sudo apt-get -y install podman fuse-overlayfs

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download image (intel)
        uses: actions/download-artifact@v4
        with:
          name: wkdev-sdk-intel.tar
  
      - name: Download image (arm64)
        uses: actions/download-artifact@v4
        with:
          name: wkdev-sdk-a64.tar

      - name: Deploy image
        run: |
          podman load < wkdev-sdk-intel.tar
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io --username=${GITHUB_REPOSITORY_OWNER} --password-stdin
          podman manifest create $REPO:$WKDEV_SDK_TAG
          for IMGTAG in arm64 intel; do \
              podman manifest add $REPO:$WKDEV_SDK_TAG docker://$REPO:IMGTAG; \
          done
          podman manifest push --all $REPO:$WKDEV_SDK_TAG
          
